### Bessa Nicole T. Tamarra

1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matrix.

In [4]:
import numpy as np

def determinant(matrix):
    # Check if the matrix is square
    if len(matrix) != len(matrix[0]):
        raise ValueError("Input matrix must be square for determinant calculation")

    # Base case for 2x2 matrix
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    det = 0
    for i in range(len(matrix)):
        det += ((-1) ** i) * matrix[0][i] * determinant(minor(matrix, 0, i))

    return det

def minor(matrix, row, col):
    return [row[:col] + row[col + 1:] for row in (matrix[:row] + matrix[row + 1:])]

def eigendecomposition(matrix):
    # Check if the matrix is square
    if len(matrix) != len(matrix[0]):
        raise ValueError("Input matrix must be square for eigendecomposition")

    # Calculate eigenvalues and eigenvectors using numpy for simplicity
    eigenvalues, eigenvectors = np.linalg.eig(matrix)

    return eigenvalues, eigenvectors

# Generate a random 3x3 matrix
random_matrix = np.random.rand(3, 3)

print("Random Matrix:")
print(random_matrix)

# Test determinant function
det_result = determinant(random_matrix)
print("\nDeterminant:", det_result)

# Test eigendecomposition function
eigenvalues, eigenvectors = eigendecomposition(random_matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Random Matrix:
[[0.46266615 0.51901765 0.77268805]
 [0.47844286 0.16587242 0.91515579]
 [0.99982092 0.91071421 0.09441092]]


ValueError: operands could not be broadcast together with shapes (0,3) (2,3) 